name: chatview
description: A Flutter package that allows you to integrate Chat View with highly customization options.
version: 1.3.1
issue_tracker: https://github.com/SimformSolutionsPvtLtd/flutter_chatview/issues
repository: https://github.com/SimformSolutionsPvtLtd/flutter_chatview

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  grouped_list: ^5.1.2
  intl:
  flutter_linkify: ^6.0.0
  url_launcher: ^6.1.7
  emoji_picker_flutter: ^1.6.0
  http: ^1.1.0
  html: ^0.15.1
  any_link_preview: ^3.0.0
  progress_indicators: ^1.0.0
  image_picker: '>=0.8.9 <2.0.0'
  audio_waveforms: ^1.0.4
  voice_message_package: ^2.1.4
  flutter_vibrate: ^1.3.0
  record: ^4.4.4
  lottie: any
  clipboard: ^0.1.3
  fluttertoast: ^8.2.4
  photo_view: ^0.14.0
  drag_down_to_pop: ^1.0.0

  # For formatting time locale in message receipts
  timeago: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  assets:
    - packages/chatview/assets/json/dustbin.json

