import 'package:chatview/chatview.dart';

class Data {
  static const profileImage =
      "https://raw.githubusercontent.com/SimformSolutionsPvtLtd/flutter_showcaseview/master/example/assets/simform.png";
  static final messageList = [
    Message(
      id: '1',
      isSpam: false,
      message: "Hi!",
      readAt: 'Today 11:01 AM',
      spamMessage: '',
      createdAt: DateTime.now(),
      sendBy: '1',
      // userId of who sends the message
      status: MessageStatus.read,
      messageTime: '${DateTime.now().hour}:${DateTime.now().minute}',
    ),
    Message(
      id: '2',
      isSpam: false,
      readAt: 'Today 11:01 AM',
      spamMessage: '',
      message: "Hi!",
      createdAt: DateTime.now(),
      sendBy: '2',
      status: MessageStatus.read,
      messageTime: '${DateTime.now().hour}:${DateTime.now().minute}',
    ),
    Message(
      id: '3',
      isSpam: false,
      spamMessage: '',
      readAt: 'Today 11:01 AM',
      message: "We can meet?I am free",
      createdAt: DateTime.now(),
      sendBy: '1',
      status: MessageStatus.read,
      messageTime: '${DateTime.now().hour}:${DateTime.now().minute}',
    ),
    Message(
      id: '4',
      spamMessage: '',
      message: "Can you write the time and place of the meeting?",
      createdAt: DateTime.now(),
      sendBy: '1',
      readAt: 'Today 11:01 AM',
      isSpam: false,
      status: MessageStatus.read,
      messageTime: '${DateTime.now().hour}:${DateTime.now().minute}',
    ),
    Message(
      id: '5',
      spamMessage: '',
      message: "That's fine",
      createdAt: DateTime.now(),
      sendBy: '2',
      isSpam: false,
      readAt: 'Today 11:01 AM',
      reaction: Reaction(reactions: ['\u{2764}'], reactedUserIds: ['1']),
      status: MessageStatus.read,
      messageTime: '${DateTime.now().hour}:${DateTime.now().minute}',
    ),
    Message(
      id: '6',
      spamMessage: '',
      message: "When to go ?",
      createdAt: DateTime.now(),
      sendBy: '3',
      readAt: 'Today 11:01 AM',
      isSpam: false,
      status: MessageStatus.read,
      messageTime: '${DateTime.now().hour}:${DateTime.now().minute}',
    ),
    Message(
      id: '7',
      spamMessage: '',
      message: "I guess Simform will reply",
      createdAt: DateTime.now(),
      sendBy: '4',
      readAt: 'Today 11:01 AM',
      isSpam: false,
      status: MessageStatus.read,
      messageTime: '${DateTime.now().hour}:${DateTime.now().minute}',
    ),
    Message(
      id: '8',
      spamMessage: '',
      message: "https://bit.ly/3JHS2Wl",
      createdAt: DateTime.now(),
      sendBy: '2',
      readAt: 'Today 11:01 AM',
      isSpam: false,
      status: MessageStatus.read,
      replyMessage: const ReplyMessage(
        message: "Can you write the time and place of the meeting?",
        replyTo: '1',
        replyBy: '2',
        messageId: '4',
      ),
      messageTime: '${DateTime.now().hour}:${DateTime.now().minute}',
    ),
    Message(
      id: '9',
      spamMessage: '',
      readAt: 'Today 11:01 AM',
      message: "Done",
      isSpam: false,
      createdAt: DateTime.now(),
      sendBy: '1',
      status: MessageStatus.read,
      messageTime: '${DateTime.now().hour}:${DateTime.now().minute}',
    ),
    Message(
      id: '10',
      message: "Thank you!!",
      status: MessageStatus.read,
      isSpam: false,
      readAt: 'Today 11:01 AM',
      spamMessage: '',
      createdAt: DateTime.now(),
      sendBy: '1',
      messageTime: '${DateTime.now().hour}:${DateTime.now().minute}',
      // reaction: Reaction(
      //   reactions: ['\u{2764}', '\u{2764}', '\u{2764}', '\u{2764}'],
      //   reactedUserIds: ['2', '4', '3', '1'],
      // ),
    ),
    Message(
      id: '11',
      message: "https://miro.medium.com/max/1000/0*s7of7kWnf9fDg4XM.jpeg",
      createdAt: DateTime.now(),
      isSpam: false,
      readAt: 'Today 11:01 AM',
      spamMessage: '',
      messageType: MessageType.image,
      sendBy: '1',
      reaction: Reaction(reactions: ['\u{2764}'], reactedUserIds: ['2']),
      status: MessageStatus.read,
      messageTime: '${DateTime.now().hour}:${DateTime.now().minute}',
    ),
    Message(
      id: '12',
      message: "🤩🤩",
      createdAt: DateTime.now(),
      sendBy: '2',
      isSpam: false,
      readAt: 'Today 11:01 AM',
      spamMessage: '',
      status: MessageStatus.read,
      messageTime: '${DateTime.now().hour}:${DateTime.now().minute}',
    ),
    Message(
      id: '13',
      messageType: MessageType.voice,
      spamMessage: '',
      readAt: 'Today 11:01 AM',
      message:
          "https://back.qurancourses.technoraft.com/storage/742/audio_1703590388030.m4a",
      createdAt: DateTime.now(),
      sendBy: '1',
      isSpam: false,
      status: MessageStatus.read,
      messageTime: '${DateTime.now().hour}:${DateTime.now().minute}',
    ),
    Message(
      id: '14',
      messageType: MessageType.voice,
      spamMessage: '',
      readAt: 'Today 11:01 AM',
      message:
          "https://back.qurancourses.technoraft.com/storage/742/audio_1703590388030.m4a",
      createdAt: DateTime.now(),
      isSpam: false,
      sendBy: '2',
      status: MessageStatus.read,
      messageTime: '${DateTime.now().hour}:${DateTime.now().minute}',
    ),
  ];
}
